# Generated by Django 6.0 on 2025-12-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_live_link_project_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
    ]
